### ISSUE TITLE
Grammar Issues

### ISSUE THREAD

**Issue by YakupAltay** [node101-io/events#11]
@gergineth 
'Istanbul connects two continents **like** node101 connects Turkish blockchain enthusiasts to the world. We enable you to reach university student clubs, blockchain communities, and developers that drive the ecosystem.'

'like' sounds pretty slang here, isn't 'as' better?

**Comment by YakupAltay** [comment]
@gergineth 
'PARTNER YOU NEED' 

'partner' might be perceived as a verb here. I suggest we should add 'THE' to the beginning.

**Comment by YakupAltay** [comment]
@gergineth 
'node101 is an Istanbul based proof of stake validator that produces user-friendly solutions to the problems of the decentralized internet. In addition to the technical solutions and pain-point solver products it offers to blockchain projects, it organizes gatherings, summits, and workshops that feed the Turkish developer ecosystem. Moreover, It provides content to the ecosystem with blog posts, podcast episodes, and video content published on Library node101.'

Such a long paragraph doesn't attract the audience, and we should turn each sentence into a paragraph.

**Comment by metekoraygergin** [comment]
I don't think that the paragraph that tells a bit about node101 is long enough to be chopped into new paragraphs. I found the very first two issues that you had found, acceptable indeed. I will act tomorrow according to them!
